// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbkmjtnwayyykmrsyify.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpia21qdG53YXl5eWttcnN5aWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjIyODgsImV4cCI6MjA3MjQ5ODI4OH0.xG1WV5xp3Cv--dpBnp15JVfT65ehpY8GjjHGQUjSNLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});